#!/usr/bin/env python3
"""Build prompts.js for the GPT Image 2 prompt library page.

Parses the generated README.md into structured prompt records and writes them
to prompts.js as `window.PROMPTS = [...]`, so index.html works when opened
directly from disk (no web server / fetch / CORS needed).

Usage:
    python3 prompt-library/build.py            # parses ../README.md
    python3 prompt-library/build.py README_zh.md
"""
import json
import os
import re
import sys

BLOCK_RE = re.compile(r"^### No\. \d+: (.+?)\s*$", re.MULTILINE)
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def section(body, header):
    m = re.search(r"####\s*" + re.escape(header) + r"\s*\n(.*?)(?:\n#### |\Z)",
                  body, re.DOTALL)
    return m.group(1).strip() if m else ""


def code_block(body, header):
    sec = section(body, header)
    fence = re.search(r"```[a-zA-Z]*\n(.*?)```", sec, re.DOTALL)
    return (fence.group(1) if fence else sec).strip()


def parse(text):
    matches = list(BLOCK_RE.finditer(text))
    # Featured section comes before "## 📋 All Prompts"; mark those as featured.
    all_idx = text.find("## 📋 All Prompts")
    out = []
    for i, m in enumerate(matches):
        heading = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end]

        category, title = (heading.split(" - ", 1) if " - " in heading
                           else ("", heading))
        images = re.findall(r'<img[^>]+src="([^"]+)"', section(body, "🖼️ Generated Images"))
        details = section(body, "📌 Details")
        author = re.search(r"\*\*Author:\*\*\s*\[([^\]]+)\]\(([^)]+)\)", details)
        source = re.search(r"\*\*Source:\*\*\s*\[([^\]]+)\]\(([^)]+)\)", details)
        link = re.search(r"\((https://youmind\.com/[^)]+)\)", body)

        out.append({
            "category": category.strip(),
            "title": title.strip(),
            "description": section(body, "📖 Description"),
            "prompt": code_block(body, "📝 Prompt"),
            "images": images,
            "author": author.group(1) if author else "",
            "authorLink": author.group(2) if author else "",
            "source": source.group(2) if source else "",
            "link": link.group(1) if link else "",
            "featured": all_idx != -1 and m.start() < all_idx,
        })
    return out


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "README.md"
    path = src if os.path.isabs(src) else os.path.join(REPO_ROOT, src)
    with open(path, encoding="utf-8") as f:
        prompts = parse(f.read())

    payload = json.dumps(prompts, ensure_ascii=False, indent=1)
    out_path = os.path.join(os.path.dirname(__file__), "prompts.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build.py — do not edit by hand.\n")
        f.write("window.PROMPTS = " + payload + ";\n")
    print(f"Wrote {len(prompts)} prompts to {out_path}")


if __name__ == "__main__":
    main()
